name: Continuous delivery
on:
  push:
    branches:
      - develop
      - main
  workflow_dispatch:

jobs:
  build_and_push:
    name: Build and push image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        with:
          context: .
          push: true
          file: Dockerfile.release
          tags: |
            ${{ env.ECR_REGISTRY }}/template-node:${{ github.sha }}
            ${{ env.ECR_REGISTRY }}/template-node:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
